language: php
dist: trusty

php:
  - 5.6
  - 7.1

install:
  - composer install --prefer-source --no-interaction --dev
  - composer require php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    travis_retry php vendor/bin/php-coveralls -v;
    fi
