language: php
dist: trusty

php:
  - '5.6'
  - '7.1'

install:
  - composer install
  - curl -L https://github.com/phan/phan/releases/download/1.2.7/phan.phar -o phan.phar;
  - composer require php-coveralls/php-coveralls

before_script:
  - phpenv config-rm xdebug.ini
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    pecl install ast;
    fi

script:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    php phan.phar
    fi
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    travis_retry php vendor/bin/php-coveralls -v;
    fi
