language: php
dist: trusty

services:
  - mysql

php:
  - 5.6
  - 7.0

before_install:
  - mysql -e 'CREATE DATABASE sufel DEFAULT CHARACTER SET utf8;'

before_script:
  - mysql -u root sufel < data/schema.sql
  - mysql -u root sufel -e "INSERT INTO company VALUES ('20000000001', 'COMPANY', '$2y$10$RtEbbUZPVkJPOLdV8i1vBOACAz30Drt/riIEoYdKjzBD8EPIhXf4.', 1)";
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: 
  - vendor/bin/phpunit --configuration phpunit.xml
